# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05dc8fcf8c05619e3c314595231fba6f6d186ac2b96a088d83d02f916c17ed5f6621f668e1d65fbb668abdd537e85d7d0855ceeae96572b37a2806eab103398b

test:
  secret_key_base: 2748e295b31e1861f3d278fa8b7653b173bd8a1db259850eb9851afef9ba3438e00ae7445b9f124e5ed15180efebd9deee70b916be820b4635a8c4b7cef0777b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
